server:
  port: 8080

spring:
  application:
    name: quiz-gateway
  cloud:
    gateway:
      routes:
        - id: quiz-backend
          uri: lb://quiz-backend
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=0
        - id: quiz-frontend
          uri: http://localhost:5173
          predicates:
            - Path=/**
          filters:
            - RewritePath=/(?<path>.*), /$\{path}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
