server:
  port: 8080

spring:
  application:
    name: quiz-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:5173
              - http://127.0.0.1:5173
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: auth
          uri: lb://quiz-backend
          predicates:
            - Path=/api/auth/**
        - id: quiz
          uri: lb://quiz-backend
          predicates:
            - Path=/api/**
        - id: ws
          uri: lb:ws://quiz-backend
          predicates:
            - Path=/ws/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


